### ISSUE TITLE
index.html and index.njk created - Output conflict

### ISSUE THREAD

**Issue by jasonblewis** [jmhobbs/wp-to-11ty#5]
on my full blog conversion, wp-to-11ty creates an index.html and index.njk

```
> blog@1.0.0 serve
> npx @11ty/eleventy --serve

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] Output conflict: multiple input files are writing to `_site/index.html`. Use distinct `permalink` values to resolve this conflict.
[11ty]   1. ./index.njk
[11ty]   2. ./index.html (via DuplicatePermalinkOutputError)
[11ty] 
[11ty] Original error stack trace: (Repeated output has been truncated…)
[11ty]     at TemplateMap.checkForDuplicatePermalinks (/home/jason/projects/emacstragic-convert-to-md/site/node_modules/@11ty/eleventy/src/TemplateMap.js:803:13)
[11ty]     at TemplateMap.cache (/home/jason/projects/emacstragic-convert-to-md/site/node_modules/@11ty/eleventy/src/TemplateMap.js:488:10)
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async TemplateWriter._createTemplateMap (/home/jason/projects/emacstragic-convert-to-md/site/node_modules/@11ty/eleventy/src/TemplateWriter.js:330:5)
[11ty]     at async TemplateWriter.generateTemplates (/home/jason/projects/emacstragic-convert-to-md/site/node_modules/@11ty/eleventy/src/TemplateWriter.js:360:5)
[11ty]     at async TemplateWriter.write (/home/jason/projects/emacstragic-convert-to-md/site/node_modules/@11ty/eleventy/src/TemplateWriter.js:407:23)
[11ty]     at async Eleventy.executeBuild (/home/jason/projects/emacstragic-convert-to-md/site/node_modules/@11ty/eleventy/src/Eleventy.js:1191:13)
[11ty]     at async Eleventy.watch (/home/jason/projects/emacstragic-convert-to-md/site/node_modules/@11ty/eleventy/src/Eleventy.js:1014:18)
[11ty] Wrote 0 files in 0.94 seconds (v2.0.1)
jason@snow:~/projects/emacstragic-convert-to-md/site$ ls -l index*
-rw-r--r-- 1 jason jason 152 May 11 10:57 index.html
-rw-r--r-- 1 jason jason 304 May 11 10:57 index.njk
```

**Comment by jmhobbs** [comment]
Ah, this is related to using a post as the front/home page.

I think the fix here will be to not write the `index.njk` if there is an `index.html` written out.
